name: Build LaTeX PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: red

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          args: -interaction=nonstopmode -file-line-error -halt-on-error

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: documento-final
          path: main.pdf